name: MikkHS
version: 0.1.0.0
github: "dpwiz/MikkHS"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# synopsis: Short description of your package
# category: Graphics

#description: .

dependencies:
- base >= 4.7 && < 5

language: GHC2021
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

include-dirs:
  - cbits

library:
  source-dirs: src
  c-sources:
    - cbits/mikktspace.c
  install-includes:
    - mikktspace.h

executables:
  MikkHS:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MikkHS

tests:
  MikkHS-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MikkHS
